### ISSUE TITLE
Login/logout not steady

### ISSUE THREAD

**Issue by pyw2102** [Advanced-Software-Engineering-Project/events-calendar#1]
The app is unable to allow each user to maintain their own private space. When the app is complete, there should be a different event page for different users; this version of the app does not support that right now. 

To find this issue: 
1. Log In with an account. You will be led to the events page.
2. Click “back” on browser. You will be brought back to a Login Page.
3. Click “forward” on browser. You will still see the generic events page

**Comment by pw2393** [comment]
Backend flask extensions to use:
* https://flask-login.readthedocs.io/en/latest/
* https://flask-security.readthedocs.io/en/latest/

#### Temporary solution
Login to view events
* Successful login
* Server returns `user_id` to front
* Front redirects page to `events/index.html` with known `user_id`
* Front passes url `/eventss`(yes, two 's' lol) with 'GET' method, at the same time passing `user_id` back to server.
* Server verify if this `user_id` is a logged one, i.e. in a logging session.
* Server returns all events and user's favorite. (For this step's detail, refer to [Favorite Issue](https://github.com/Advanced-Software-Engineering-Project/events-calendar/issues/3))

**Comment by pw2393** [comment]
Remaining problem:
redirecting after logging in
