### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by pyw2102** [Advanced-Software-Engineering-Project/events-calendar#3]
Users should be able to "favorite" events by clicking on the heart associated to each event. When users log into their account, they can see the events that they favorited in the past.

**Comment by pw2393** [comment]
#### Temporary Solution
Right after server verifies that the `user_id` (front passed on url `/eventss`) is a logged one.
1. Server returns all events and user's favorite. 
    * all events: a _json_ file, generated from _a list of python dictionary_, containing information of _all_ events queried from SQL database.
    * user's favortie: a _json_ file, generated from _a list of string_, containing all `id` of user's favorite events.
2. At default, user will see _all_ events after front redirects to `events/index.html` and a `SEE FAVORITE` button somewhere.
3. User clicks that `SEE FAVORITE` button
4. Now only user's favorite events show on page, and a `SEE ALL` button somewhere.
5. User clicks that `SEE ALL` button, then back to step 2.

Note that, _for this issue only_, front has no more interaction with server at step 2 or 5 (that is after server returns events and favorites).
